### ISSUE TITLE
Important thing regarding deb files

### ISSUE THREAD

**Issue by kodxana** [AlphaAtlas/VapourSynthColab#10]
Hey I have important question.
Do you have copy of this files :
vapoursynth_48-1_amd64.deb
imagemagick_7.0.9-8-1_amd64.deb

Issue is that bintray is now gone and we cant access this files anymore.

**Comment by Jerchongkong** [comment]
Apparently the original creator totally abandoned this project, it can no longer be downloaded from his page.
Fortunately, I managed to save those two files since they are the most important pieces.

https://drive.google.com/file/d/1K2_tBgRLb_kYR-2AYJEGuUt4r9V6Gkeq/view?usp=sharing

https://drive.google.com/file/d/1aoT3kzeVYqSlhAeTY7OdbuUvBlHaVucj/view?usp=sharing
